#pragma once

#define MAX_STEAM_CONTROLLERS 8

enum
{
	MAX_JOYSTICKS = 1,
	MOUSE_BUTTON_COUNT = 5,
	MAX_NOVINT_DEVICES = 2
};

enum JoystickAxis_t
{
	JOY_AXIS_X = 0,
	JOY_AXIS_Y,
	JOY_AXIS_Z,
	JOY_AXIS_R,
	JOY_AXIS_U,
	JOY_AXIS_V,
	MAX_JOYSTICK_AXES
};

enum
{
	MS_WM_XBUTTONDOWN = 0x020B,
	MS_WM_XBUTTONUP = 0x020C,
	MS_WM_XBUTTONDBLCLK = 0x020D,
	MS_MK_BUTTON4 = 0x0020,
	MS_MK_BUTTON5 = 0x0040
};

enum InputEventType_t
{
	IE_ButtonPressed = 0,
	IE_ButtonReleased,
	IE_ButtonDoubleClicked,
	IE_AnalogValueChanged,
	IE_FirstSystemEvent = 100,
	IE_Quit = IE_FirstSystemEvent,
	IE_ControllerInserted,
	IE_ControllerUnplugged,
	IE_FirstVguiEvent = 1000,
	IE_FirstAppEvent = 2000
};

struct InputEvent_t
{
	int m_nType = 0;
	int m_nTick = 0;
	int m_nData = 0;
	int m_nData2 = 0;
	int m_nData3 = 0;
};

typedef enum
{
	SK_NULL,
	SK_BUTTON_A,
	SK_BUTTON_B,
	SK_BUTTON_X,
	SK_BUTTON_Y,
	SK_BUTTON_UP,
	SK_BUTTON_RIGHT,
	SK_BUTTON_DOWN,
	SK_BUTTON_LEFT,
	SK_BUTTON_LEFT_BUMPER,
	SK_BUTTON_RIGHT_BUMPER,
	SK_BUTTON_LEFT_TRIGGER,
	SK_BUTTON_RIGHT_TRIGGER,
	SK_BUTTON_LEFT_GRIP,
	SK_BUTTON_RIGHT_GRIP,
	SK_BUTTON_LPAD_TOUCH,
	SK_BUTTON_RPAD_TOUCH,
	SK_BUTTON_LPAD_CLICK,
	SK_BUTTON_RPAD_CLICK,
	SK_BUTTON_LPAD_UP,
	SK_BUTTON_LPAD_RIGHT,
	SK_BUTTON_LPAD_DOWN,
	SK_BUTTON_LPAD_LEFT,
	SK_BUTTON_RPAD_UP,
	SK_BUTTON_RPAD_RIGHT,
	SK_BUTTON_RPAD_DOWN,
	SK_BUTTON_RPAD_LEFT,
	SK_BUTTON_SELECT,
	SK_BUTTON_START,
	SK_BUTTON_STEAM,
	SK_BUTTON_INACTIVE_START,
	SK_VBUTTON_F1,
	SK_VBUTTON_F2,																																										
	SK_VBUTTON_F3,
	SK_VBUTTON_F4,
	SK_VBUTTON_F5,
	SK_VBUTTON_F6,
	SK_VBUTTON_F7,
	SK_VBUTTON_F8,
	SK_VBUTTON_F9,
	SK_VBUTTON_F10,
	SK_VBUTTON_F11,
	SK_VBUTTON_F12,
	SK_MAX_KEYS
} sKey_t;

enum ESteamPadAxis
{
	LEFTPAD_AXIS_X,
	LEFTPAD_AXIS_Y,
	RIGHTPAD_AXIS_X,
	RIGHTPAD_AXIS_Y,
	LEFT_TRIGGER_AXIS,
	RIGHT_TRIGGER_AXIS,
	GYRO_AXIS_PITCH,
	GYRO_AXIS_ROLL,
	GYRO_AXIS_YAW,
	MAX_STEAMPADAXIS = GYRO_AXIS_YAW
};

enum
{
	LASTINPUT_KBMOUSE = 0,
	LASTINPUT_CONTROLLER = 1,
	LASTINPUT_STEAMCONTROLLER = 2
};

enum GameActionSet_t
{
	GAME_ACTION_SET_NONE = -1,
	GAME_ACTION_SET_MENUCONTROLS = 0,
	GAME_ACTION_SET_FPSCONTROLS,
	GAME_ACTION_SET_IN_GAME_HUD,
	GAME_ACTION_SET_SPECTATOR
};

enum GameActionSetFlags_t
{
	GAME_ACTION_SET_FLAGS_NONE = 0,
	GAME_ACTION_SET_FLAGS_TAUNTING = (1 << 0)
};

enum JoystickType_t
{
	INPUT_TYPE_GENERIC_JOYSTICK = 0,
	INPUT_TYPE_X360,
	INPUT_TYPE_STEAMCONTROLLER
};